/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2014 Kurento (http://kurento.org/)
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the GNU Lesser General Public License
 * (LGPL) version 2.1 which accompanies this distribution, and is available at
 * http://www.gnu.org/licenses/lgpl-2.1.html
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var ChecktypeError = kurentoClient.checkType.ChecktypeError;

var OpenCVFilter = kurentoClient.register.abstracts.OpenCVFilter;

/**
 * Create an element
 *
 * @classdesc
 *  testingModule2 interface. Documentation about the module
 *
 * @extends module:filtersfilters/abstracts.OpenCVFilter
 *
 * @constructor module:testingmodule2.testingModule2
 */
function testingModule2(){
  testingModule2.super_.call(this);
};
inherits(testingModule2, OpenCVFilter);

/**
 * @alias module:testingmodule2.testingModule2.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
testingModule2.constructorParams = {
  mediaPipeline: {
    type: 'MediaPipeline',
    required: true
  },
};

/**
 * @alias module:testingmodule2.testingModule2.events
 *
 * @extend module:filtersfilters/abstracts.OpenCVFilter.events
 */
testingModule2.events = OpenCVFilter.events;

module.exports = testingModule2;

testingModule2.check = function(key, value)
{
  if(!(value instanceof testingModule2))
    throw ChecktypeError(key, testingModule2, value);
};
